// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-W_RcO3tK7HvixKftshK46S5cy8bh-wE',
    appId: '1:596255721571:web:04ee7cde348b4c916b9056',
    messagingSenderId: '596255721571',
    projectId: 'bracelet-sync-health',
    authDomain: 'bracelet-sync-health.firebaseapp.com',
    storageBucket: 'bracelet-sync-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvZ_Qc_SrREgXfMFhlryW-r4wq8nj-rGs',
    appId: '1:596255721571:android:d9211df3261c902a6b9056',
    messagingSenderId: '596255721571',
    projectId: 'bracelet-sync-health',
    storageBucket: 'bracelet-sync-health.firebasestorage.app',
  );
}
